AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template to create a new AWS Secret storing credentials for a consumer group of a specific confluent kafka cluster
  If you

Metadata:
  Author: johnpreston
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Cluster Settings
        Parameters:
          - ClusterId
          - BootstrapEndpoint
          - BootstrapPort
          - SchemaRegistryUrl
      - Label:
          default: Consumer group settings
        Parameters:
          - ConsumerGroupName
          - ConsumerGroupUsername
          - ConsumerGroupPassword
      - Label:
          default: Schema Registry credentials
        Parameters:
          - SchemaRegistryGroupUsername
          - SchemaRegistryGroupPassword

Parameters:
  ClusterId:
    Type: String
  BootstrapEndpoint:
    Type: String
  BootstrapPort:
    Type: Number
    MinValue: 1024
    MaxValue: 65535

  ConsumerGroupName:
    Type: String
  ConsumerGroupUsername:
    Type: String
    NoEcho: True
  ConsumerGroupPassword:
    Type: String
    NoEcho: True

  SchemaRegistryUrl:
    Type: String
  SchemaRegistryGroupUsername:
    Type: String
    NoEcho: True
  SchemaRegistryGroupPassword:
    Type: String
    NoEcho: True
  License:
    Default: none
    Type: String
    NoEcho: True

Conditions:
  NoLicense: !Equals [ !Ref License, "none" ]

Resources:
  KafkaSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/kafka/${ClusterId}/${ConsumerGroupName}'
      Description: "Secret for Confluent Control Center"
      SecretString: !If
        - NoLicense
        - !Sub |
          {
            "SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
            "CONTROL_CENTER_BOOTSTRAP_SERVERS": "${BootstrapEndpoint}:${BootstrapPort}",
            "CONTROL_CENTER_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
            "CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
            "CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ConsumerGroupUsername}\" password=\"${ConsumerGroupPassword}\";",
            "CONFLUENT_LICENSE": "${License}",
            "CONTROL_CENTER_LICENSE": "${License}"
          }
        - !Sub |
          {
            "SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
            "CONTROL_CENTER_BOOTSTRAP_SERVERS": "${BootstrapEndpoint}:${BootstrapPort}",
            "CONTROL_CENTER_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
            "CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
            "CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ConsumerGroupUsername}\" password=\"${ConsumerGroupPassword}\";",
          }
