AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template to create a new AWS Secret storing credentials for a consumer group of a specific confluent kafka cluster

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Cluster Settings
        Parameters:
          - ClusterId
          - BootstrapEndpoint
          - BootstrapPort
          - SchemaRegistryUrl
          - ClusterName
      - Label:
          default: Connect general settings
        Parameters:
          - ClusterConnectUsername
          - ClusterConnectPassword
      - Label:
          default: Connect consumer settings
        Parameters:
          - ClusterConsumerUsername
          - ClusterConsumerPassword
      - Label:
          default: Connect producer settings
        Parameters:
          - ClusterProducerUsername
          - ClusterProducerPassword
      - Label:
          default: Schema Registry credentials
        Parameters:
          - SchemaRegistryGroupUsername
          - SchemaRegistryGroupPassword

Parameters:
  ClusterId:
    Type: String
  BootstrapEndpoint:
    Type: String
  BootstrapPort:
    Type: Number
    MinValue: 1024
    MaxValue: 65535

  ClusterName:
    Type: String

  ClusterConnectUsername:
    Type: String
    NoEcho: True
  ClusterConnectPassword:
    Type: String
    NoEcho: True

  ClusterProducerUsername:
    Type: String
    NoEcho: True
  ClusterProducerPassword:
    Type: String
    NoEcho: True

  ClusterConsumerUsername:
    Type: String
    NoEcho: True
  ClusterConsumerPassword:
    Type: String
    NoEcho: True


  SchemaRegistryUrl:
    Type: String
  SchemaRegistryGroupUsername:
    Type: String
    NoEcho: True
  SchemaRegistryGroupPassword:
    Type: String
    NoEcho: True

Resources:
  KafkaSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/kafka/${ClusterId}/${ClusterName}'
      Description: "Secret for Confluent Connect Cluster credentials"
      SecretString: !Sub |
        {
          "SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
          "SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
          "CONNECT_BOOTSTRAP_SERVERS": "${BootstrapEndpoint}:${BootstrapPort}",
          "CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
          "CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryGroupUsername}:${SchemaRegistryGroupPassword}",
          "CONNECT_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterConnectUsername}\" password=\"${ClusterConnectPassword}\";",
          "CONNECT_CONSUMER_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterConsumerUsername}\" password=\"${ClusterConsumerPassword}\";",
          "CONNECT_PRODUCER_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterProducerUsername}\" password=\"${ClusterProducerPassword}\";",
          "CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterConsumerUsername}\" password=\"${ClusterConsumerPassword}\";",
          "CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterProducerUsername}\" password=\"${ClusterProducerPassword}\";"
        }
