Description: IAM role for cloudformation to use to create resources
Parameters:
  CiAccountId:
    Type: String
    AllowedPattern: '[0-9]{12}'
  CiKmsKeyId:
    Type: String
    AllowedPattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
  ArtifactsBucketName:
    Type: String
    AllowedPattern: '[a-z0-9.-]+'
  CloudformationTemplatesBucketName:
    Type: String
    AllowedPattern: '[a-z0-9.-]+'
Resources:
  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: AllowCreateRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowIamRoleCreation
                Effect: Allow
                Resource:
                  - '*'
                Action:
                  - iam:GetRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:ListRoleTags
                  - iam:UntagRole
                  - iam:TagRole
                  - iam:PutRolePermissionsBoundary
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:UpdateRoleDescription
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePermissionsBoundary
                  - iam:AddRoleToInstanceProfile
                  - iam:ListInstanceProfilesForRole
                  - iam:PassRole
                  - iam:CreateServiceLinkedRole
                  - iam:DetachRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:DeleteRolePolicy
                  - iam:UpdateRole
                  - iam:ListRolePolicies
                  - iam:GetRolePolicy
        - PolicyName: KmsDecryptData
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: DecryptEncryptArtifacts
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                Resource:
                  - !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${CiAccountId}:key/${CiKmsKeyId}'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:GetBucket*
                Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucketName}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucketName}/*'
                Sid: AllowRwToArtifactsBucket
              - Action:
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:GetBucket*
                Effect: Allow
                Sid: GetCloudformationTemplates
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudformationTemplatesBucketName}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudformationTemplatesBucketName}/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'cloudformation.${AWS::URLSuffix}'
            Condition:
              Bool:
                aws:SecureTransport: true

  CrossAccountRoleForPipeline:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: KmsDecryptData
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: DecryptEncryptArtifacts
                Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource:
                  - !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${CiAccountId}:key/${CiKmsKeyId}'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - s3:PutObject*
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Effect: Allow
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucketName}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucketName}/*'
                Sid: AllowRwToArtifactsBucket
              - Action:
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Effect: Allow
                Sid: GetCloudformationTemplates
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudformationTemplatesBucketName}'
                  - !Sub 'arn:${AWS::Partition}:s3:::${CloudformationTemplatesBucketName}/*'
        - PolicyName: AccessForCloudFormation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - iam:PassRole
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - !Sub 'cloudformation.${AWS::URLSuffix}'
                Effect: Allow
                Resource:
                  - !GetAtt 'CloudformationRole.Arn'
                Sid: AllowsPipelineToPassRoleToCfn
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Effect: Allow
                Resource: '*'
                Sid: AllowsCloudFormationAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:${AWS::Partition}:iam::${CiAccountId}:root'
            Condition:
              Bool:
                aws:SecureTransport: true

Outputs:
  CfnRoleArn:
    Value: !GetAtt 'CloudformationRole.Arn'
  CfnRoleId:
    Value: !GetAtt 'CloudformationRole.RoleId'
  CrossRoleArn:
    Value: !GetAtt 'CrossAccountRoleForPipeline.Arn'
  CrossRoleId:
    Value: !GetAtt 'CrossAccountRoleForPipeline.RoleId'
