Description: Template for Shared-ECR
Metadata:
  Author: John Preston
Parameters:
  RepositoryName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]+'
  ProdAccountId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cicd/accounts/prod/id
#    Type: String
#    AllowedPattern: [0-9]{12}
  DevAccountId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cicd/accounts/dev/id
#    Type: String
#    AllowedPattern: [0-9]{12}
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref 'RepositoryName'
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: AllowPullFromAccounts
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${ProdAccountId}:root
                - !Sub arn:${AWS::Partition}:iam::${DevAccountId}:root
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:DescribeImages
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - ecr:ListImages
Outputs:
  RepositoryArn:
    Value: !GetAtt 'Repository.Arn'
  RepositoryName:
    Value: !Ref 'Repository'
