Description: Template for Shared-ECR
Metadata:
  Author: John Preston
Parameters:
  RepositoryName:
    Type: String
    AllowedPattern: [a-zA-Z0-9-]
  ProdAccountId:
    Type: String
    AllowedPattern: [0-9]{12}
  DevAccountId:
    Type: String
    AllowedPattern: [0-9]{12}
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref 'RepositoryName'
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
          - Sid: AllowPullFromAccounts
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::{ProdAccountId}:root
                - arn:aws:iam::${DevAccountId}:root
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:DescribeImages
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - ecr:ListImages
Outputs:
  RepositoryArn:
    Export:
      Name: !Sub '${Repository}-ECRRepository-Arn'
    Value: !GetAtt 'Repository.Arn'
  RepositoryName:
    Export:
      Name: !Sub '${RepositoryName}-ECRRepository-Name'
    Value: !Ref 'Repository'
